platform :ios, '5.0'

pod 'AFNetworking', '1.2.1'
pod 'AFRaptureXMLRequestOperation', '1.0.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.3'
pod 'MagicalRecord', '~> 2.2'
pod 'KGModal', '~> 0.0.1'
pod 'MHNatGeoViewControllerTransition', '~> 1.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'UALogger', '~> 0.2.3'
pod 'Reachability', '~> 3.1.1'
pod 'RegexKitLite', '~> 4.0'
pod 'SSKeychain', '~> 1.2.1'
pod 'TTTAttributedLabel'
pod 'TPKeyboardAvoiding', '~> 1.1'
pod 'UIAlertView+Blocks', '~> 0.7'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.3'
pod 'SevenSwitch', '~> 1.3.0'

